### ISSUE TITLE
White Screen, Debug log not really helping

### ISSUE THREAD

**Issue by muhwyndhamhp** [NiceneNerd/BCML#210]
**Objective**
Install BCML

**What Expected**
Working after install

**What happened**
- White Screen
- Debug version not showing anything in CMD
- If with Debug version I press `Ctrl+C` it shows this log:
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\wyndh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bcml\_server.py", line 17, in start_server
    httpd.serve_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt
```

**How to Reproduce**
- install Python 3.7 via Windows Store
- `pip install bcml`
- open bcml as admin

**Installed requirements**
- Python 3.7 from Windows Store (also happened with Python 3.8 from Windows Store)
- PIP version 20.1.1
- VC-Redist 2015-2019 x86 
- VC-Redist 2015-2019 x64
- Edge WebView2

Any help/heads up is appreciated.

**Comment by muhwyndhamhp** [comment]
Never mind, solved with `pip install cefpython3`

**Comment by NiceneNerd** [comment]
I still don't understand what causes this for some people when using WebView2 instead of CEF. I need to figure that out still, so I'll reopen this.

**Comment by NiceneNerd** [comment]
Oh, but I do see you ran BCML as admin. Before installing CEF, did you ever try *not* running as admin?

**Comment by muhwyndhamhp** [comment]
I've trying to run it both as admin and not. Both ways do not work until I install cefpython3. Thank you for the hard work btw.

**Comment by GingerAvalanche** [comment]
If I were to hazard a guess, BCML attempts to create the UI using webview, fails, the error gets silenced (whether by BCML or by WebView itself), and then the program enters the idle loop.

That may or may not have already been obvious, by the KeyboardInterrupt occurring in `serveforever()`

**Comment by semillakan6** [comment]
I installed cefpython3 but its still a white void please help
