### ISSUE TITLE
Infinite updates

### ISSUE THREAD

**Issue by flow54** [NiceneNerd/BCML#365]
BCML keeps prompting "Update Available" even after updating, and will crash when trying to install a mod

**Comment by NiceneNerd** [comment]
Should be fixed now

**Comment by HGStone** [comment]
it is not fixed. it still prompts for updates everytime you open bcml even though i am already on 3.9.12

**Comment by flow54** [comment]
yeah I'm still running into the same issue with BCML
