### ISSUE TITLE
BCML doesn't open after succesfull instalation

### ISSUE THREAD

**Issue by Osifp6** [NiceneNerd/BCML#529]
I'm using Python 3.8 with Windows 11. Nothing happens either by using the `bcml` command or by opening the shortcut. When I run the `bcml-debug` it shows: 

[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\?scar\AppData\Local\Programs\Python\Python38\Scripts\bcml-debug.exe\__main__.py", line 7, in <module>
    sys.exit(main_debug())
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 155, in main_debug
    main(True)
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 149, in main
    webview.start(gui=gui, debug=debug, http_server=True, func=_oneclick.process_arg)
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
  File "c:\users\?scar\appdata\local\programs\python\python38\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

**Comment by GingerAvalanche** [comment]
This appears to be an old pythonnet error, that is fixed by updating .NET - I'm not sure which .NET is the minimum version that works, since I have side-by-side installations of every version for the past 6 years, and have never had this issue, but try .NET 6 or .NET 7

Reopen the issue if that doesn't solve it.

**Comment by Osifp6** [comment]
I reopen the issue as installing .NET 6/7 doesn't fix it. Same error appears in debug.

**Comment by GingerAvalanche** [comment]
Hrm. What pythonnet version did it install? Run the command `pip show pythonnet` in the command line and it'll tell you.

If it's pythonnet 3.0.0 or 3.0.1, try rolling back to 2.5.2 with the command `pip install pythonnet==2.5.2` and seeing if that works.

**Comment by Osifp6** [comment]
It worked! I can open it now and it's perfectly funcional. Thank you very much!
